[webserver]
loglevel = "Warn"
[webserver.cors]
allow_all_origins = true

[[datasource]]
name = "postgis_db"
[datasource.postgis]
url = "${DB_DSN}"

[[collection]]
name = "lakes"
title = "Lakes"
description = "Lake features"
[collection.postgis]
datasource = "postgis_db"
sql = """
SELECT 
    Uid, 
    SubId, 
    ST_AsGeoJSON(ST_SetSRID(geom, 3005)) AS geojson 
FROM lakes 
"""
fid_field = "subid"
geometry_field = "geojson"
queryable_fields = ["Uid","SubId"]

[[collection]]
name = "rivers"
title = "Rivers"
description = "Rivers Features"
[collection.postgis]
datasource = "postgis_db"
sql = """
SELECT 
    Uid, 
    SubId, 
    IsLake, 
    DowSubId, 
    ST_AsGeoJSON(ST_SetSRID(geom, 3005)) AS geojson 
FROM rivers 
"""
fid_field = "subid"
geometry_field = "geojson"
queryable_fields = ["Uid","SubId"]

[[grid]]
json = "assets/BCAlbersCustomGrid.json"

[[tileset]]
name = "water_tiles"

[[tileset.cache_control]]
max_age = 86400 # Cache for 1 day
minzoom = 0
maxzoom = 12

[[tileset.tms]]
id = "BCAlbersCustomGrid"

[tileset.postgis]
datasource = "postgis_db"
extent = [217522, 376304, 5660707, 4543560]

# Rivers Layer
[[tileset.postgis.layer]]
name = "rivers"
geometry_type = "LINESTRING"

[[tileset.postgis.layer.query]]
sql = """
  SELECT  Uid, SubId, IsLake, DowSubId, ST_SetSRID(geom, 3005) AS geom
  FROM rivers
  WHERE geom && ST_MakeEnvelope($1, $2, $3, $4, 3005)
"""

# Lakes Layer
[[tileset.postgis.layer]]
name = "lakes"
geometry_type = "POLYGON"

[[tileset.postgis.layer.query]]
sql = """
  SELECT Uid, SubId, IsLake, ST_SetSRID(geom, 3005) AS geom
  FROM lakes
  WHERE geom && ST_MakeEnvelope($1, $2, $3, $4, 3005)
"""


