name: Docker Publishing
on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.pcicdevops_at_dockerhub_username }}
          password: ${{ secrets.pcicdevops_at_dockerhub_password }}

      - name: Build and Publish Demo App
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/app/Dockerfile
          push: true
          tags: |
            pcic/bbox-demo-app:${{ github.ref_name }}
            ${{ github.ref_name == 'main' && 'pcic/bbox-demo-app:latest' || '' }}

      - name: Build and Publish Data Import
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/data-import/Dockerfile
          push: true
          tags: |
            pcic/bbox-demo-data-import:${{ github.ref_name }}
            ${{ github.ref_name == 'main' && 'pcic/bbox-demo-data-import:latest' || '' }}

      - name: Build and Publish PostGIS
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/PostGIS/Dockerfile
          push: true
          tags: |
            pcic/bbox-demo-postgis:${{ github.ref_name }}
            ${{ github.ref_name == 'main' && 'pcic/bbox-demo-postgis:latest' || '' }}
      
      - name: Build and Publish BBOX server
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/BBOX/Dockerfile
          push: true
          tags: |
            pcic/bbox-demo-server:${{ github.ref_name }}
            ${{ github.ref_name == 'main' && 'pcic/bbox-demo-server:latest' || '' }}
